# -*- coding: utf-8 -*-
"""Copy of HW4_Part1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kzhGv17SKJfP9YK2aC_Xs0SLwZTenwVo
"""

import pandas as pd
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

"""**Q1** Please use Pandas to read olympic_medals.csv and use parallel_categories function from plotly.express to visualize proportions of medal type for each gender from since year 2000. Please see the example in the Python notebook we walked through in the class."""

import pandas as pd
medals = pd.read_csv('/content/drive/MyDrive/DATA/olympic_medals.csv')

#Please use this cell to create your your figure. Please use Year column to color your graph.
import plotly.express as px

upper = medals[~medals.iloc[:,3].between(0, 1999, inclusive=False)]


px.parallel_categories(upper, dimensions=['Year', 'Medal', 'Gender'], color = 'Year')

"""**Q2** Please inspect the code below and observe how values are plotted by running it. Then, read the 2016elections.csv from the DATA folder and select rows for AR, MI, CA, and WI. Then, utilize stacked bar plot, to stack vote percentages for Trump, Clinton, Johson, and Others. Please see 'pct_clinton',	'pct_trump',	'pct_johnson',	'pct_other' columns. Make sure that your x tick labels are those four states above."""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
 
# create DataFrame
df = pd.DataFrame({'High Temp': [28, 30, 34, 38, 45, 42,
                                 38, 35, 32, 28, 25, 21],
                   'Low Temp': [22, 26, 30, 32, 41, 38,
                                32, 31, 28, 22, 15, 15],
                   'Avg Temp': [25, 28, 32, 35, 43, 40,
                                35, 33, 30, 25, 20, 18]},
                  index=['Jan', 'Feb', 'Mar', 'Apr', 'May',
                         'Jun', 'Jul', 'Aug', 'Sep', 'Oct',
                         'Nov', 'Dec'])
 
 
# create stacked bar chart for monthly temperatures
df.plot(kind='bar', stacked=True, color=['red', 'skyblue', 'green'])
 
# labels for x & y axis
plt.xlabel('Months')
plt.ylabel('Temp ranges in Degree Celsius')
 
# title of plot
plt.title('Monthly Temperatures in a year')

#You can use this cell to write your code. It is doable at most 4 lines of code. 
election = pd.read_csv('/content/drive/MyDrive/DATA/2016elections.csv')

votes = election.loc[(election['st'] == 'AR') | (election['st'] == 'MI') | (election['st'] == 'CA') | (election['st'] == 'WI')] 
votes.head(25)

percent = votes[['pct_trump', 'pct_clinton', 'pct_johnson', 'pct_other']]

"""Question 4"""